# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  coffeeservice:
    image: coffeeservice
    build:
      context: .
      dockerfile: CoffeeService/Dockerfile
    ports:
      - 80
